import './globals.css';
if (typeof window !== "undefined") {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  require("bootstrap/dist/js/bootstrap")
}
import "@style/index.scss";
import AppProvider from '@shared/contextApi/AppProvider';
import ReduxProvider from '@shared/redux/provider';
import { ToastContainer } from 'react-toastify';
import process from 'process';
import Script from 'next/script';

export const metadata = {
  title: 'Open Banking Demo',
  description: 'Open Banking Demo application',
};

const configScript = `window.config = {
  apiBaseUrl: '${process.env.API_BASE_URL}'
};`

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <head>
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <meta name="description" content="Generated by create next app" />
          <meta name="robots" content="noindex, follow" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
          />
          <link rel="icon" href="/favicon.ico" />
        </head>

        <Script id="config-script">{configScript}</Script>

        <body suppressHydrationWarning={true}>
          <ReduxProvider>
            <AppProvider>
              {children}
            </AppProvider>
            <ToastContainer
              position="top-left"
              autoClose={1000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          </ReduxProvider>
        </body>
      </html>
    </>
  )
}
